### ISSUE TITLE
Proposal: Cooperate with ipsilon project

### ISSUE THREAD

**Issue by spacekpe** [FedOAuth/FedOAuth#61]
It seems that FedOAuth and Ipsilon projects are somehow similar. Maybe it would be beneficial to cooperate and possibly share some code.

From Ipsilon project homepage:
"The server is a pluggable selfcontained mod_wsgi application that provides federated SSO to web applications. User authentication is always performed against a separate Identity Management system (for example a FreeIPA server), and communication with application is done using a federation protocol like SAML (the only one currently implemented), OpenId?, etc.."

Ipsilon project home page is hosted on:
https://fedorahosted.org/ipsilon/

Have a nice day!

**Comment by puiterwijk** [comment]
This cooperation has started and the merge completed.
Thanks, @spacekpe for getting me in contact with Ipsilon upstream!
