### ISSUE TITLE
Cannot authenticate against https://pypi.python.org/pypi?:action=openid

### ISSUE THREAD

**Issue by jnpkrn** [FedOAuth/FedOAuth#63]
Tried that, unsuccessfully:

> Something went wrong
> 
> We're sorry! An error occurred trying to fulfill your request.

Not sure if this is related to:

> must support OpenID 2.0

**Comment by puiterwijk** [comment]
No, this is an issue at PyPI.
FedOAuth fully implements OpenID 2.0.

I have reported the issue to the PyPI people, but last time I asked them they didn't want to diagnose further since they "would be having a new major release soon".
